# Generated by Django 6.0.3 on 2026-03-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_sellerprofile'),
        ('accounts', '0003_auto_20260329_2005'),
    ]

    operations = [
    ]
