# Generated by Django 6.0.3 on 2026-03-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_selleruser_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
    ]
